In [47]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
df=pd.read_csv('loan_approved.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [49]:
df['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [50]:
df = pd.get_dummies(df, columns=['Married'])

In [56]:
df.head()

,Loan_ID,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved),Married_No,Married_Yes,Gender_Female,Gender_Male
0,LP001002,0,0.0,No,5849,0.0,NaN,360.0,1.0,Urban,Y,True,False,False,True
1,LP001003,1,0.0,No,4583,1508.0,128.0,360.0,1.0,Rural,N,False,True,False,True
2,LP001005,0,0.0,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,False,True,False,True
3,LP001006,0,1.0,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,False,True,False,True
4,LP001008,0,0.0,No,6000,0.0,141.0,360.0,1.0,Urban,Y,True,False,False,True

In [52]:
df = pd.get_dummies(df, columns=['Gender'])

In [8]:
df['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [54]:
#df_encoded=OrdinalEncoder(categories=[['Graduate', 'Not Graduate']])
encoder = OrdinalEncoder()

In [55]:
df['Education'] = encoder.fit_transform(df[['Education']])

In [34]:
df['Education']

0      0.0
1      0.0
2      0.0
3      1.0
4      0.0
      ...
609    0.0
610    0.0
611    0.0
612    0.0
613    0.0
Name: Education, Length: 614, dtype: float64

In [15]:
df['Self_Employed'].unique()

array(['No', 'Yes', nan], dtype=object)

In [57]:
df = pd.get_dummies(df, columns=['Self_Employed'])

In [58]:
encoder = LabelEncoder()

In [59]:
df['Loan_Status (Approved)'] = encoder.fit_transform(df[['Loan_Status (Approved)']])

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [60]:
df['Loan_Status (Approved)']

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status (Approved), Length: 614, dtype: int64

In [61]:
df

,Loan_ID,Dependents,Education,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved),Married_No,Married_Yes,Gender_Female,Gender_Male,Self_Employed_No,Self_Employed_Yes
0,LP001002,0,0.0,5849,0.0,NaN,360.0,1.0,Urban,1,True,False,False,True,True,False
1,LP001003,1,0.0,4583,1508.0,128.0,360.0,1.0,Rural,0,False,True,False,True,True,False
2,LP001005,0,0.0,3000,0.0,66.0,360.0,1.0,Urban,1,False,True,False,True,False,True
3,LP001006,0,1.0,2583,2358.0,120.0,360.0,1.0,Urban,1,False,True,False,True,True,False
4,LP001008,0,0.0,6000,0.0,141.0,360.0,1.0,Urban,1,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,0,0.0,2900,0.0,71.0,360.0,1.0,Rural,1,True,False,True,False,True,False
610,LP002979,3+,0.0,4106,0.0,40.0,180.0,1.0,Rural,1,False,True,False,True,True,False
611,LP002983,1,0.0,8072,240.0,253.0,360.0,1.0,Urban,1,False,True,False,True,True,False
612,LP002984,2,0.0,7583,0.0,187.0,360.0,1.0,Urban,1,False,True,False,True,True,False
613,LP002990,0,0.0,4583,0.0,133.0,360.0,0.0,Semiurban,0,True,False,True,False,False,True