In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('imdb-top-1000.csv')

In [4]:
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [5]:
genres = movies.groupby('Genre')

In [9]:
# Applying builtin aggregation fuctions on groupby objects
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [11]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)
# find the top 3 genres by total earning

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [12]:
# find the genre with highest avg IMDB rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [13]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [14]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [22]:
studentss=pd.read_csv('studentss.csv')
#studentss

In [29]:
reg_month2=pd.read_csv('reg-month2.csv')
reg_month2.tail()

    student_id  course_id
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [19]:
studentss.merge(reg_month2,how='inner',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23         10
1            1       Kailash Harjo       23          9
2            2         Esha Butala        1          5
3            3      Parveen Bhalla        3          5
4            7        Tarun Thaker        9          7
5            7        Tarun Thaker        9          2
6            7        Tarun Thaker        9          6
7           11  David Mukhopadhyay       20          8
8           11  David Mukhopadhyay       20         10
9           12          Radha Dutt       19         10
10          12          Radha Dutt       19          1
11          12          Radha Dutt       19          5
12          12          Radha Dutt       19          7
13          14    Pranab Natarajan       22          9
14          14    Pranab Natarajan       22          6
15          14    Pranab Natarajan       22          4
16          14    Pranab Natarajan       22          1
17          16        Elias Dodiya       25          7
18          16        Elias Dodiya       25          3
19          17        Yasmin Palan        7         10
20          18     Fardeen Mahabir       13          8
21          22          Yash Sethi       21          5
22          22          Yash Sethi       21          6
23          23      Chhavi Lachman       18          9
24          23      Chhavi Lachman       18          5

In [24]:
courses=pd.read_csv('courses.csv')

In [30]:
courses.tail()

    course_id course_name  price
7           8      pandas   1099
8           9      plotly    699
9          10     pyspark   2499
10         11       Numpy    699
11         12         C++   1299

In [27]:
# left join
courses.merge(reg_month2,how='left',on='course_id')

    course_id       course_name  price  student_id
0           1            python   2499        12.0
1           1            python   2499        14.0
2           1            python   2499        38.0
3           2               sql   3499         7.0
4           3     data analysis   4999        16.0
5           4  machine learning   9999        14.0
6           5           tableau   2499         3.0
7           5           tableau   2499        12.0
8           5           tableau   2499         2.0
9           5           tableau   2499        22.0
10          5           tableau   2499        23.0
11          6          power bi   1899        14.0
12          6          power bi   1899         7.0
13          6          power bi   1899        22.0
14          7          ms sxcel   1599        16.0
15          7          ms sxcel   1599         7.0
16          7          ms sxcel   1599        12.0
17          8            pandas   1099        11.0
18          8            pandas   1099        18.0
19          8            pandas   1099        50.0
20          9            plotly    699        14.0
21          9            plotly    699         1.0
22          9            plotly    699        23.0
23          9            plotly    699        42.0
24         10           pyspark   2499        12.0
25         10           pyspark   2499        17.0
26         10           pyspark   2499         1.0
27         10           pyspark   2499        11.0
28         11             Numpy    699         NaN
29         12               C++   1299         NaN

In [31]:
# right join
temp_df = pd.DataFrame({
    'student_id':[26,27,28],
    'name':['Nitish','Ankit','Rahul'],
    'partner':[28,26,17]
})

students = pd.concat([studentss,temp_df],ignore_index=True)

In [33]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2
25          26              Nitish       28
26          27               Ankit       26
27          28               Rahul       17

In [34]:
students.merge(reg_month2,how='right',on='student_id')

    student_id                name  partner  course_id
0            3      Parveen Bhalla      3.0          5
1           16        Elias Dodiya     25.0          7
2           12          Radha Dutt     19.0         10
3           12          Radha Dutt     19.0          1
4           14    Pranab Natarajan     22.0          9
5            7        Tarun Thaker      9.0          7
6            7        Tarun Thaker      9.0          2
7           16        Elias Dodiya     25.0          3
8           17        Yasmin Palan      7.0         10
9           11  David Mukhopadhyay     20.0          8
10          14    Pranab Natarajan     22.0          6
11          12          Radha Dutt     19.0          5
12          12          Radha Dutt     19.0          7
13          18     Fardeen Mahabir     13.0          8
14           1       Kailash Harjo     23.0         10
15           1       Kailash Harjo     23.0          9
16           2         Esha Butala      1.0          5
17           7        Tarun Thaker      9.0          6
18          22          Yash Sethi     21.0          5
19          22          Yash Sethi     21.0          6
20          23      Chhavi Lachman     18.0          9
21          23      Chhavi Lachman     18.0          5
22          14    Pranab Natarajan     22.0          4
23          14    Pranab Natarajan     22.0          1
24          11  David Mukhopadhyay     20.0         10
25          42                 NaN      NaN          9
26          50                 NaN      NaN          8
27          38                 NaN      NaN          1

In [36]:
reg_month2.tail()

    student_id  course_id
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [38]:
reg_month2.merge(students,how='left',on='student_id')

    student_id  course_id                name  partner
0            3          5      Parveen Bhalla      3.0
1           16          7        Elias Dodiya     25.0
2           12         10          Radha Dutt     19.0
3           12          1          Radha Dutt     19.0
4           14          9    Pranab Natarajan     22.0
5            7          7        Tarun Thaker      9.0
6            7          2        Tarun Thaker      9.0
7           16          3        Elias Dodiya     25.0
8           17         10        Yasmin Palan      7.0
9           11          8  David Mukhopadhyay     20.0
10          14          6    Pranab Natarajan     22.0
11          12          5          Radha Dutt     19.0
12          12          7          Radha Dutt     19.0
13          18          8     Fardeen Mahabir     13.0
14           1         10       Kailash Harjo     23.0
15           1          9       Kailash Harjo     23.0
16           2          5         Esha Butala      1.0
17           7          6        Tarun Thaker      9.0
18          22          5          Yash Sethi     21.0
19          22          6          Yash Sethi     21.0
20          23          9      Chhavi Lachman     18.0
21          23          5      Chhavi Lachman     18.0
22          14          4    Pranab Natarajan     22.0
23          14          1    Pranab Natarajan     22.0
24          11         10  David Mukhopadhyay     20.0
25          42          9                 NaN      NaN
26          50          8                 NaN      NaN
27          38          1                 NaN      NaN

In [39]:
# outer join
students.merge(reg_month2,how='outer',on='student_id').tail(10)

    student_id             name  partner  course_id
34          23   Chhavi Lachman     18.0        9.0
35          23   Chhavi Lachman     18.0        5.0
36          24     Radhika Suri     17.0        NaN
37          25  Shashank D’Alia      2.0        NaN
38          26           Nitish     28.0        NaN
39          27            Ankit     26.0        NaN
40          28            Rahul     17.0        NaN
41          38              NaN      NaN        1.0
42          42              NaN      NaN        9.0
43          50              NaN      NaN        8.0

In [40]:
# find total revenue generated
total = reg_month2.merge(courses,how='inner',on='course_id')['price'].sum()
total

np.int64(65072)